# Generated by Django 3.2.16 on 2022-11-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveequityresult',
            name='below_three',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
