# Generated by Django 3.2.16 on 2022-11-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderticket', '0002_liveequityresult_below_three'),
    ]

    operations = [
        migrations.AddField(
            model_name='equitythree',
            name='change_perc',
            field=models.FloatField(default=0),
        ),
    ]
